(defun i-ching (number)
  (interactive "nNumber: ")
  (w3m-find-file (format "~/emacs/i-ching/%s.html" number))
  (fundamental-mode)
  (read-only-mode 0)
  ;; (delete-matching-lines "^|-")
  (set-mark (point))
  (forward-line 7)
  (delete-region (mark) (point)))
