(defun i-ching (number)
  (interactive "nNumber: ")
  (let ((text (read-from-minibuffer "question? ")))
    (w3m-find-file (format "~/emacs/i-ching/%s.html" number))
    (fundamental-mode)
    (read-only-mode 0)
    (set-mark (point))
    (forward-line 7)
    (delete-region (mark) (point))
    (insert (format "%s  %s\n\n" (current-time-string) text))
    (while (re-search-forward "|" nil t)
      (replace-match " "))
    (set-mark (point-max))
    (goto-char (point-max))
    (forward-line -6)
    (delete-region (mark) (point))
    (goto-char (point-min))
    (forward-line 1)
    (delete-region (point-min) (point))
    (read-only-mode 1)
    (write-file (format "~/i-ching/%s.txt" (replace-regexp-in-string " " "-" (current-time-string))))))
